/* ============================================================
   LOCAL LORE ORACLE — SETTINGS v1.0
   Module configuration for LLM endpoint, model, and prompts.

   Default deployment: Ollama running on a Win11 gaming PC
   (Ryzen 7 5800X / RX 6800 XT / 32GB RAM) connected to
   the Foundry server via Tailscale. Gemma 4 E4B is the
   recommended model — 6GB VRAM, fast inference, 128K context.
   ============================================================ */

const MODULE_ID = "local-lore-oracle";

export function registerSettings() {

  game.settings.register(MODULE_ID, "apiEndpoint", {
    name: "API Endpoint URL",
    hint: "Your Ollama endpoint. For Tailscale: use your PC's Tailscale IP (e.g., http://100.x.x.x:11434/v1/chat/completions). For same-machine: http://localhost:11434/v1/chat/completions",
    scope: "world",
    config: true,
    type: String,
    default: "http://localhost:11434/v1/chat/completions",
  });

  game.settings.register(MODULE_ID, "modelName", {
    name: "Model Name",
    hint: "Ollama model to use. Recommended: gemma4:e4b (needs 6GB VRAM, RX 6800 XT or better). Fallback: gemma3:4b (CPU-friendly, 3GB RAM).",
    scope: "world",
    config: true,
    type: String,
    default: "gemma4:e4b",
  });

  game.settings.register(MODULE_ID, "systemPrompt", {
    name: "System Prompt",
    hint: "The persona and guardrails prompt. {KNOWLEDGE_CONTEXT} is replaced with the knowledge base at runtime.",
    scope: "world",
    config: false,
    type: String,
    default: "",
  });

  game.settings.register(MODULE_ID, "knowledgeContext", {
    name: "Knowledge Context",
    hint: "Player-safe knowledge injected into the system prompt. Generated by Build-Oracle-Context.ps1.",
    scope: "world",
    config: false,
    type: String,
    default: "",
  });

  game.settings.register(MODULE_ID, "temperature", {
    name: "Temperature",
    hint: "Response creativity. Lower = focused, higher = creative. 0.7–0.8 is good for Tassle's personality.",
    scope: "world",
    config: true,
    type: Number,
    default: 0.75,
    range: { min: 0.1, max: 1.5, step: 0.05 },
  });

  game.settings.register(MODULE_ID, "maxTokens", {
    name: "Max Response Tokens",
    hint: "Maximum response length. 400–600 gives 2–4 paragraph answers. Higher = longer responses but slower.",
    scope: "world",
    config: true,
    type: Number,
    default: 512,
    range: { min: 128, max: 2048, step: 64 },
  });

  game.settings.register(MODULE_ID, "cooldownSeconds", {
    name: "Cooldown (seconds)",
    hint: "Minimum time between /lore queries. Prevents spamming the LLM. 0 to disable.",
    scope: "world",
    config: true,
    type: Number,
    default: 15,
    range: { min: 0, max: 60, step: 5 },
  });

  // Settings menu button for prompt editing
  game.settings.registerMenu(MODULE_ID, "promptEditor", {
    name: "Edit Oracle Prompt & Knowledge",
    label: "Open Prompt Editor",
    hint: "Edit Tassle's system prompt and paste/update the player-safe knowledge context.",
    icon: "fas fa-scroll",
    type: OraclePromptEditor,
    restricted: true,
  });
}

/* ----------------------------------------------------------
   PROMPT EDITOR — FormApplication for the system prompt
   and knowledge context. Too large for settings text inputs.
   ---------------------------------------------------------- */

class OraclePromptEditor extends FormApplication {

  static get defaultOptions() {
    return foundry.utils.mergeObject(super.defaultOptions, {
      id: "oracle-prompt-editor",
      title: "Tasslequill's Desk — Prompt & Knowledge Editor",
      template: `modules/${MODULE_ID}/templates/prompt-editor.html`,
      width: 720,
      height: 650,
      resizable: true,
      closeOnSubmit: true,
    });
  }

  getData() {
    return {
      systemPrompt: game.settings.get(MODULE_ID, "systemPrompt"),
      knowledgeContext: game.settings.get(MODULE_ID, "knowledgeContext"),
    };
  }

  async _updateObject(event, formData) {
    await game.settings.set(MODULE_ID, "systemPrompt", formData.systemPrompt);
    await game.settings.set(MODULE_ID, "knowledgeContext", formData.knowledgeContext);
    ui.notifications.info("Tassle's prompt and knowledge updated.");
  }
}
