/* ============================================================
   LOCAL LORE ORACLE — SETTINGS v1.1
   Module configuration for LLM endpoint, model, and prompts.
   Supports both local Ollama and cloud APIs (Gemini, OpenAI).
   ============================================================ */

const MODULE_ID = "local-lore-oracle";

export function registerSettings() {

  game.settings.register(MODULE_ID, "apiEndpoint", {
    name: "API Endpoint URL",
    hint: "Gemini: https://generativelanguage.googleapis.com/v1beta/openai/chat/completions — Ollama: http://100.x.x.x:11434/v1/chat/completions",
    scope: "world",
    config: true,
    type: String,
    default: "https://generativelanguage.googleapis.com/v1beta/openai/chat/completions",
  });

  game.settings.register(MODULE_ID, "apiKey", {
    name: "API Key",
    hint: "For Gemini: your Google AI Studio API key. For Ollama: leave blank (no auth needed). Get a Gemini key at https://aistudio.google.com/apikey",
    scope: "world",
    config: true,
    type: String,
    default: "",
  });

  game.settings.register(MODULE_ID, "modelName", {
    name: "Model Name",
    hint: "Gemini: gemini-2.5-flash (recommended). Ollama: gemma4:e4b or gemma3:4b.",
    scope: "world",
    config: true,
    type: String,
    default: "gemini-2.5-flash",
  });

  game.settings.register(MODULE_ID, "systemPrompt", {
    name: "System Prompt",
    hint: "The persona and guardrails prompt. {KNOWLEDGE_CONTEXT} is replaced with the knowledge base at runtime.",
    scope: "world",
    config: false,
    type: String,
    default: "",
  });

  game.settings.register(MODULE_ID, "knowledgeContext", {
    name: "Knowledge Context",
    hint: "Player-safe knowledge injected into the system prompt. Generated by Build-Oracle-Context.ps1.",
    scope: "world",
    config: false,
    type: String,
    default: "",
  });

  game.settings.register(MODULE_ID, "temperature", {
    name: "Temperature",
    hint: "Response creativity. 0.75–0.85 is good for Tassle's personality.",
    scope: "world",
    config: true,
    type: Number,
    default: 0.80,
    range: { min: 0.1, max: 1.5, step: 0.05 },
  });

  game.settings.register(MODULE_ID, "maxTokens", {
    name: "Max Response Tokens",
    hint: "Maximum response length. 500–700 gives 2–4 paragraph answers.",
    scope: "world",
    config: true,
    type: Number,
    default: 600,
    range: { min: 128, max: 2048, step: 64 },
  });

  game.settings.register(MODULE_ID, "cooldownSeconds", {
    name: "Cooldown (seconds)",
    hint: "Minimum time between /lore queries. Prevents spam. 0 to disable.",
    scope: "world",
    config: true,
    type: Number,
    default: 15,
    range: { min: 0, max: 60, step: 5 },
  });

  game.settings.registerMenu(MODULE_ID, "promptEditor", {
    name: "Edit Oracle Prompt & Knowledge",
    label: "Open Prompt Editor",
    hint: "Edit Tassle's system prompt and paste/update the player-safe knowledge context.",
    icon: "fas fa-scroll",
    type: OraclePromptEditor,
    restricted: true,
  });
}

/* ----------------------------------------------------------
   PROMPT EDITOR
   ---------------------------------------------------------- */

class OraclePromptEditor extends FormApplication {

  static get defaultOptions() {
    return foundry.utils.mergeObject(super.defaultOptions, {
      id: "oracle-prompt-editor",
      title: "Tasslequill's Desk — Prompt & Knowledge Editor",
      template: `modules/${MODULE_ID}/templates/prompt-editor.html`,
      width: 720,
      height: 650,
      resizable: true,
      closeOnSubmit: true,
    });
  }

  getData() {
    return {
      systemPrompt: game.settings.get(MODULE_ID, "systemPrompt"),
      knowledgeContext: game.settings.get(MODULE_ID, "knowledgeContext"),
    };
  }

  async _updateObject(event, formData) {
    await game.settings.set(MODULE_ID, "systemPrompt", formData.systemPrompt);
    await game.settings.set(MODULE_ID, "knowledgeContext", formData.knowledgeContext);
    ui.notifications.info("Tassle's prompt and knowledge updated.");
  }
}
